### ISSUE TITLE
Auto Add Package

### ISSUE THREAD

**Issue by boynukaline** [aniruddhahar/Unity-Autosave#1]
How can we make this package added automatically everytime a new project is created?

**Comment by aniruddhahar** [comment]
You could create an empty project, and add this package. Then you can copy
that project and use it as a template.

Alternatively you can edit the packages manifest to download this package
from your local copy or git.

I've kept it isolated so that upgrading the package should be as simple
as possible.

**Comment by boynukaline** [comment]
Thank you first option is great
